name: Fetch Weather

on:
  push:
    branches:
      - main

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script with secret
        env:
          MY_API_KEY: "bdf5a4056376bfd95284755824ba216a"
        run: python main.py
